### ISSUE TITLE
Fix circular imports in serializers

### ISSUE THREAD

**Issue by karolina-siemieniuk-morawska** [cern-sis/issues-inspire#388]
```

...:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-82a7ec573853> in <module>
----> 1 from inspirehep.records.marshmallow.literature.common import PublicationInfoItemSchemaV1

~/src/inspirehep/backend/inspirehep/records/marshmallow/literature/__init__.py in <module>
      7 # flake8: noqa
      8
----> 9 from .authors import LiteratureAuthorsSchema
     10 from .base import (
     11     LiteratureAdminSchema,

~/src/inspirehep/backend/inspirehep/records/marshmallow/literature/authors.py in <module>
     10
     11 from ..fields import NestedWithoutEmptyObjects
---> 12 from .common import AuthorSchemaV1
     13 from .common.author import SupervisorSchema
     14

~/src/inspirehep/backend/inspirehep/records/marshmallow/literature/common/__init__.py in <module>
     11 from .collaboration import CollaborationSchemaV1
     12 from .collaboration_with_suffix import CollaborationWithSuffixSchemaV1
---> 13 from .conference_info_item import ConferenceInfoItemSchemaV1
     14 from .doi import DOISchemaV1
     15 from .external_system_identifier import ExternalSystemIdentifierSchemaV1

~/src/inspirehep/backend/inspirehep/records/marshmallow/literature/common/conference_info_item.py in <module>
      9
     10 from inspirehep.pidstore.api import PidStoreBase
---> 11 from inspirehep.records.api import InspireRecord
     12
     13

~/src/inspirehep/backend/inspirehep/records/api/__init__.py in <module>
     12 from .authors import AuthorsRecord  # noqa: F401
     13 from .base import InspireRecord  # noqa: F401
---> 14 from .conferences import ConferencesRecord  # noqa: F401
     15 from .data import DataRecord  # noqa: F401
     16 from .experiments import ExperimentsRecord  # noqa: F401

~/src/inspirehep/backend/inspirehep/records/api/conferences.py in <module>
      8 from inspirehep.pidstore.api.conferences import PidStoreConferences
      9 from inspirehep.records.api.base import InspireRecord
---> 10 from inspirehep.records.marshmallow.conferences import ConferencesElasticSearchSchema
     11 from inspirehep.records.models import (
     12     ConferenceLiterature,

~/src/inspirehep/backend/inspirehep/records/marshmallow/conferences/__init__.py in <module>
      7 # flake8: noqa
      8
----> 9 from .base import (
     10     ConferencesAdminSchema,
     11     ConferencesPublicListSchema,

~/src/inspirehep/backend/inspirehep/records/marshmallow/conferences/base.py in <module>
     11 from inspirehep.records.marshmallow.base import RecordBaseSchema
     12 from inspirehep.records.marshmallow.common import ContactDetailsItemWithoutEmail
---> 13 from inspirehep.records.marshmallow.conferences.common.proceeding_info_item import (
     14     ProceedingInfoItemSchemaV1,
     15 )

~/src/inspirehep/backend/inspirehep/records/marshmallow/conferences/common/proceeding_info_item.py in <module>
      7 from marshmallow import Schema, fields
      8
----> 9 from inspirehep.records.marshmallow.literature.common import PublicationInfoItemSchemaV1
     10
     11

ImportError: cannot import name 'PublicationInfoItemSchemaV1'
```

Moved from: https://github.com/inspirehep/inspirehep/issues/1648

**Comment by ioannistsanaktsidis** [comment]
Lets check if thats still relevant

**Comment by DonHaul** [comment]
this circular imports error are only ocurring when using `python` instead of the `inspirehep shell`

EDIT: there doesn't seem to be an easy and elegant way to do it.

**Comment by ioannistsanaktsidis** [comment]
Closing as currently it is not affecting us

**Comment by ioannistsanaktsidis** [comment]
EDIT: Re-opening as we need to take care of that

**Comment by ioannistsanaktsidis** [comment]
@DonHaul lets coordinate with @drjova , he has an idea about that one

**Comment by DonHaul** [comment]
Removed circular imports from `conferences` and `data` error has evolved to:

```
>>> from inspirehep.records.marshmallow.literature.common import PublicationInfoItemSchemaV1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/inspire/inspirehep/records/marshmallow/literature/__init__.py", line 9, in <module>
    from .authors import LiteratureAuthorsSchema
  File "/opt/inspire/inspirehep/records/marshmallow/literature/authors.py", line 11, in <module>
    from inspirehep.records.marshmallow.literature.common import AuthorSchemaV1
  File "/opt/inspire/inspirehep/records/marshmallow/literature/common/__init__.py", line 9, in <module>
    from .author import AuthorSchemaV1, AuthorsInfoSchemaForES
  File "/opt/inspire/inspirehep/records/marshmallow/literature/common/author.py", line 15, in <module>
    from inspirehep.records.api import AuthorsRecord
  File "/opt/inspire/inspirehep/records/api/__init__.py", line 17, in <module>
    from .literature import LiteratureRecord  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/inspire/inspirehep/records/api/literature.py", line 32, in <module>
    from inspirehep.orcid.api import push_to_orcid
  File "/opt/inspire/inspirehep/orcid/__init__.py", line 25, in <module>
    from inspirehep.orcid.converter import OrcidConverter  # noqa F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/inspire/inspirehep/orcid/converter.py", line 19, in <module>
    from inspirehep.records.api.conferences import ConferencesRecord
  File "/opt/inspire/inspirehep/records/api/conferences.py", line 9, in <module>
    from inspirehep.records.marshmallow.conferences.es import ConferencesElasticSearchSchema
  File "/opt/inspire/inspirehep/records/marshmallow/conferences/es.py", line 7, in <module>
    from inspirehep.records.marshmallow.conferences.base import ConferencesRawSchema
  File "/opt/inspire/inspirehep/records/marshmallow/conferences/base.py", line 12, in <module>
    from inspirehep.records.marshmallow.conferences.common.proceeding_info_item import (
  File "/opt/inspire/inspirehep/records/marshmallow/conferences/common/proceeding_info_item.py", line 8, in <module>
    from inspirehep.records.marshmallow.literature.common import PublicationInfoItemSchemaV1
ImportError: cannot import name 'PublicationInfoItemSchemaV1' from partially initialized module 'inspirehep.records.marshmallow.literature.common' (most likely due to a circular import) (/opt/inspire/inspirehep/records/marshmallow/literature/common/__init__.py)
```

**Comment by DonHaul** [comment]
After https://github.com/inspirehep/inspirehep/pull/3612 this issue no longer occurs. although a lot of __init__ should still be deleted

**Comment by ioannistsanaktsidis** [comment]
@DonHaul if issue no longer appears, we can close this one after deploying a spawn a new issue to cleanup the `init` . New issue can serve as a spike

**Comment by DonHaul** [comment]
Closing. to be followed up in https://github.com/cern-sis/issues-inspire/issues/972
